server:
  address: 0.0.0.0
  port: 8089
  servlet:
    context-path: /gastos-mensais

spring:
  application:
    name: gastos-mensais
  data:
    mongodb:
      uri: ${MONGODB_URI}
      data-base: ${MONGODB_DATABASE}

  jackson:
    time-zone: UTC
    serialization:
      fail-on-empty-beans: false
      WRITE_DATES_AS_TIMESTAMPS: false

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

logging:
  level:
    org.springframework.web: INFO
    org.springframework.data: DEBUG


